FROM node:20-bullseye-slim
LABEL maintainer="juandacorreo@gmail.com"

ENV NODE_ENV=development
ENV PORT=3000 

# set locale
ENV LC_ALL es_ES.UTF-8
ENV LANG es_ES.UTF-8
ENV LANGUAGE es_ES.UTF-8


# Set working directory
RUN mkdir /app
WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm ci 


# Configure entrypoint
COPY entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

# Bundle app source
COPY . . 

# Run app

EXPOSE $PORT

USER node

# Run this app when a container is launched
# base image entrypoint will add node command
CMD ["npm", "run", "start"]

