version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_DB_USER=${MONGO_DB_USER}
      - MONGO_DB_PWD=${MONGO_DB_PWD}
      - DATABASE_URL=mongodb://${MONGO_DB_USER}:${MONGO_DB_PWD}@<REMOTE_IP_OR_HOSTNAME>:27017/arasaac?authSource=admin
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    restart: unless-stopped

